### ISSUE TITLE
Problem with github_install and Remotes (in DESCRIPTION)

### ISSUE THREAD

**Issue by ewymathe** [hadley/devtools#1307] opened 2016-08-25 21:01 UTC
Hello,

I'm trying to have my package install with all of its CRAN and BioC dependencies.  In an attempt to do so, I've installed the latest github:

> devtools::install_github("hadley/devtools")

And have then tried installing my package:

```
 > install_github("ewymathe/testALTREinstall")
Downloading GitHub repo ewymathe/testALTREinstall@master
from URL https://api.github.com/repos/ewymathe/testALTREinstall/zipball/master
Installing ALTRE
Error validating server certificate for 'https://hedgehog.fhcrc.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: *.fhcrc.org
 - Valid: from Sat, 18 Oct 2014 16:52:00 GMT until Fri, 23 Nov 2018 15:15:23 GMT
 - Issuer: http://certs.godaddy.com/repository/, GoDaddy.com, Inc., Scottsdale, Arizona, US
 - Fingerprint: 55:64:9d:ce:78:a9:b0:b4:2f:df:4c:c6:59:b1:51:56:bb:5c:44:6a
(R)eject, accept (t)emporarily or accept (p)ermanently? t
svn: warning: W170000: URL 'https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks/or.Hs.eg.db' non-existent in revision 120432

svn: E200009: Could not display info for all targets because some targets don't exist
Installation failed: There was a problem retrieving the current SVN revision
Warning message:
running command ''/usr/bin/svn' info --xml --username readonly --password readonly https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks/or.Hs.eg.db' had status 1
```

In my DESCRIPTION file, I have the following Remotes line:
`Remotes: bioc::release/org.Hs.eg.db`

For some reason, some of the Bioconductor packages install readily while others (such as org.Hs.eg.db) do not.

Can you help?

Ewy

**Comment by jimhester** [comment] 2016-08-25 21:46
IIRC the certificate warning is a false positive ([reference](https://stat.ethz.ch/pipermail/bioc-devel/2013-November/004985.html)), you need to accept the certificate (once permanently) in an interactive session. Otherwise you will get the message every time you interact with the Bioconductor SVN server.  Try running `svn info https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks` from the command line first, permanately accepting the Bioconductor certificate, then trying to install your package again.

It may also be worth posting at support.bioconductor.org about the certificate warning, maybe they could change something so the certificate would be trusted without the manual intervention.

**Comment by ewymathe** [comment] 2016-08-25 22:32
Thanks for the prompt response!  Unfortunately, I'm still getting an error though.

```
Ewys-MBP:~ ewymathe$ svn info https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks
Error validating server certificate for 'https://hedgehog.fhcrc.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: *.fhcrc.org
 - Valid: from Sat, 18 Oct 2014 16:52:00 GMT until Fri, 23 Nov 2018 15:15:23 GMT
 - Issuer: http://certs.godaddy.com/repository/, GoDaddy.com, Inc., Scottsdale, Arizona, US
 - Fingerprint: 55:64:9d:ce:78:a9:b0:b4:2f:df:4c:c6:59:b1:51:56:bb:5c:44:6a
(R)eject, accept (t)emporarily or accept (p)ermanently? p
Path: Rpacks
URL: https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks
Repository Root: https://hedgehog.fhcrc.org/bioconductor
Repository UUID: bc3139a8-67e5-0310-9ffc-ced21a209358
Revision: 120436
Node Kind: directory
Last Changed Author: jspidlen@bccrc.ca
Last Changed Rev: 120432
Last Changed Date: 2016-08-25 16:34:54 -0400 (Thu, 25 Aug 2016)

```

Then in R:

```
> https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks/org.Hs.eg.db
Error: unexpected '/' in "https:/"
> install_github("ewymathe/testALTREinstall")
Downloading GitHub repo ewymathe/testALTREinstall@master
from URL https://api.github.com/repos/ewymathe/testALTREinstall/zipball/master
Installing ALTRE
svn: warning: W170000: URL 'https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks/org.Hs.eg.db' non-existent in revision 120437

svn: E200009: Could not display info for all targets because some targets don't exist
Installation failed: There was a problem retrieving the current SVN revision
Warning message:
running command ''/usr/bin/svn' info --xml --username readonly --password readonly https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_3/madman/Rpacks/org.Hs.eg.db' had status 1
```

Also, when I try to access the link in my browser, I'm being asked for authentication...

Any other thought(s)?

**Comment by ewymathe** [comment] 2016-08-29 16:14
I have played around with this a bit more and am still perplexed, thinking it is something with the install_github() function.

Specifically, I have set the repositories and am able to successfully install "org.Hs.eg.db" with install.packages():

```
> myrepos=biocinstallRepos()
> install.packages("org.Hs.eg.db",repos=myrepos)
installing the source package ‘org.Hs.eg.db’

trying URL 'https://bioconductor.org/packages/3.3/data/annotation/src/contrib/org.Hs.eg.db_3.3.0.tar.gz'
Content type 'application/x-gzip' length 69122902 bytes (65.9 MB)
====^C==
============================================
downloaded 65.9 MB

>
```
So I know my repos will grab the package.  However, if I try to install with install_github() while passing the repos, it still cannot find the package:

```
> library(devtools)
> install_github("ewymathe/testALTREinstall",repos=myrepos)
Downloading GitHub repo ewymathe/testALTREinstall@master
from URL https://api.github.com/repos/ewymathe/testALTREinstall/zipball/master
Installing ALTRE
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j4/m74j380917j4njwrrvf2fh480000gn/T/Rtmp3VEYyF/devtools762b528dbac0/ewymathe-testALTREinstall-000280d'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library'  \
  --install-tests

ERROR: dependency ‘org.Hs.eg.db’ is not available for package ‘ALTRE’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ALTRE’
Installation failed: Command failed (1)
```
Any idea what is happening?

**Comment by jimhester** [comment] 2016-08-29 17:04
org.Hs.eg.db is a Bioconductor data package, not a software package.
Devtools only supports installing software packages with install_bioc and
remotes.

It should work if you have a BiocViews entry in your DESCRIPTION and put
org.Hs.eg.db as a regular dependency (Depends, Imports, or Suggests)

**Comment by lucacerone** [comment] 2016-10-20 09:06
I am having issues too with Remotes in the DESCRIPTION.

If in R is use devtools::install_git("https://mycompany.com/project.git") the package is installed correctly.

When in the DESCRIPTION file I add:

`Remotes: git::https://mycompany.com/project.git`

then when I use `devtools::install(".")` to install the package and check that dependencies are resolved I get the error:

> Installing rpackage
> Error in vapply(remote, remote_package_name, character(1)) : 
>   values must be type 'character',
>  but FUN(X[[1]]) result is type 'logical'

**Comment by hadley** [comment] 2017-08-02 20:54
Duplicate of #1401

**Closed by hadley** 2017-08-02 20:54 UTC
Labels: bug, install
