### ISSUE TITLE
install_github() failing on Windows due to long path names

### ISSUE THREAD

**Issue by MrDAndersen** [hadley/devtools#1235] opened 2016-06-23 16:15 UTC
We have a package available for install in a sub directory `R Package/ffanalytics` at `dadrivr/FantasyFootballAnalyticsR`. Users are instructed to install this via `devtools::install_github(repo = "dadrivr/FantasyFootballAnalyticsR", subdir = "R Package/ffanalytics")`. However, Windows users are reporting that the install fails with following error

```
Error in utils::unzip(src, exdir = target) :
cannot open file ‘C:/Users/<username>/AppData/Local/Temp/RtmpMZfFU0/devtools63c36d21285/dadrivr-FantasyFootballAnalyticsR-6c6c4a9/R Markdown/SubcriptionAccuracy/subscriptionAccuracy_cache/markdown_phpextra+backtick_code_blocks/unnamed-chunk-1_af5e2a896358b9ccbc8241e876b9ce5c.RData’: No such file or directory
```

The file mentioned is not part of the package directory, so I suspect that `devtools::install_github` is downloading the entire repo and then parsing it to find the subdir with the package. Since the repo files are extracted into a temp directory (`C:/Users/<username>/AppData/Local/Temp......`) the file names get rather long when it has to go through several levels of folders. 
The interesting thing is that you can get the command to complete after a number of tries - which may be when the file paths become short enough (<256 characters)

**Comment by henrygabs** [comment] 2016-08-23 12:21
Any suggestions for a solution to or this problem?

**Comment by luisa123456** [comment] 2016-09-14 04:50
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.

**Comment by jianlingfan** [comment] 2017-02-22 03:47
I got the same problem recently, do you have a solution?

**Comment by hadley** [comment] 2017-08-02 21:00
Duplicate of #1464

**Comment by hadley** [comment] 2017-08-02 21:03
Hmmm, might actually be a different problem, so I'll keep this one open.

**Closed** 2017-08-02 21:33 UTC
Labels: bug, install
