### ISSUE TITLE
install_local fails with package file

### ISSUE THREAD

**Issue by ctbrown** [hadley/devtools#1392] opened 2016-11-06 19:59 UTC
`install_local` fails to install a local package file (`.tar.gz`) with the `devtools-1.12.0.9000` and git2r-`0.15.0.9000`.  

Here is a failing minimal example that downloads `lazyeval` and tries to install it:

```
td <- tempdir()
local_file <- file.path( td, "lazyeval_0.2.0.tar.gz" )
download.file( "https://cran.r-project.org/src/contrib/lazyeval_0.2.0.tar.gz", local_file )
install_local( local_file )
```

The error is;

> Error in value[[3L]](cond) : argument "quiet" is missing, with no default
> In addition: Warning message:
> In read.dcf(path) :
>   cannot open compressed file '/tmp/RtmpId4Wn0/lazyeval_0.2.0.tar.gz/DESCRIPTION', probable reason 'Not a directory'

Cursory examination seems to indicate that the package file is not being extracted before checking for the DESCRIPTION file.  Has the untar step been skipped?

**Comment by tersmitten** [comment] 2016-11-24 11:53
I just encountered the same problem:

```
> devtools::install_local("/home/foo/Downloads/bar_0.1.1.tar.gz")
Error in read.dcf(path) : cannot open the connection
In addition: Warning message:
In read.dcf(path) :
  cannot open compressed file '/home/foo/Downloads/bar_0.1.1.tar.gz/DESCRIPTION', probable reason 'Not a directory'
```

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS
```

**Comment by fikovnik** [comment] 2017-06-15 09:44
I encountered the same thing. The `install_url` works though:
```
 install_url("file:///path/to/testthat_1.0.2.tar.gz")
```

**Comment by hadley** [comment] 2017-08-02 20:52
Duplicate of #1346

**Closed by hadley** 2017-08-02 20:52 UTC
Labels: bug, install
