### ISSUE TITLE
default README image directory

### ISSUE THREAD

**Issue by jsta** [hadley/devtools#1477] opened 2017-03-14 19:05 UTC
A number of CRAN maintainers recently received the following message about README image locations:

> It was recently pointed out to us that some README.html files (generated
from the corresponding README.md ones) on the CRAN package web pages are
incomplete, missing 'local' images not available from the web page and
in most cases actually not even shipped with the package.  This clearly
should be changed, so we will move to using '--self-contained' for the
pandoc conversion to ensure that the README.html files are "complete".

> Of course, this implies that all 'local' images used in README.md are
needed in the package sources.

> If the images are also used for vignettes or Rd files, you can put them
in the 'vignettes' or 'man/figures' directories.  Otherwise, please put
them in the top-level 'tools' directory, or a subdirectory of it.

> The CRAN incoming checks in r-devel were changed to perform the pandoc
conversion checks with '--self-contained', and hence will warn about
missing images.

Would it be possible to change the default image directory target (`fig.path`) of `use_readme_rmd()` to `man/figures` or `tools` per CRAN instructions above?

**Comment by hadley** [comment] 2017-05-22 13:56
Duplicate of r-pkgs/usethis/issues/19

**Closed by hadley** 2017-05-22 13:56 UTC
