### ISSUE TITLE
binary zip file failed 

### ISSUE THREAD

**Issue by drbombe** [hadley/devtools#1428] opened 2017-01-02 13:42 UTC
Thank you for developing this great tool.

Here is my issue. The package can be successfully built and installed. But after I use
`devtools::build(binary = TRUE, args = c('--preclean'))`

The following errors happen

> Warning: running command '"zip" -r9Xq "D:/myProjects/temp2/myPkgSimple_0.1.0.zip" myPkgSimple' had status 127 running 'zip' failed

I have included path of C:\RBuildTools\3.2\bin in my path.

Also, if I use RStudio to generate a binary installation package, it succeed. Did I miss something here?

**Comment by hadley** [comment] 2017-08-01 21:34
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-08-16 18:11
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-16 18:11 UTC
Labels: reprex
