### ISSUE TITLE
load_all on package with S4 classes fails

### ISSUE THREAD

**Issue by DarwinAwardWinner** [hadley/devtools#823] opened 2015-05-28 23:12 UTC
I'm trying to do some development on BiocParallel (https://github.com/Bioconductor/BiocParallel), which defines an S4 class hierarchy across several R files. When I attempt to use `load_all()` on it, I get:

```
> load_all()
Loading BiocParallel
Error in getClass(what, where = where) (from BatchJobsParam-class.R#9) : 
  "BiocParallelParam" is not a defined class
```

This looks kind of like https://github.com/hadley/devtools/issues/623, but the error message is different, so I'm not sure if it's the same issue.

```
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grDevices datasets  parallel  graphics  stats4    stats     utils    
[8] methods   base     

other attached packages:
[1] devtools_1.8.0.9000  foreach_1.4.2        plyr_1.8.2          
[4] stringr_1.0.0        IRanges_2.2.1        ggplot2_1.0.1       
[7] S4Vectors_0.6.0      BiocGenerics_0.14.0  BiocInstaller_1.18.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6          git2r_0.10.1         futile.logger_1.4.1 
 [4] bitops_1.0-6         futile.options_1.0.0 iterators_1.0.7     
 [7] tools_3.2.0          digest_0.6.8         memoise_0.2.1       
[10] gtable_0.1.2         proto_0.3-10         httr_0.6.1          
[13] roxygen2_4.1.1       rversions_1.0.0      grid_3.2.0          
[16] snow_0.3-13          XML_3.98-1.1         reshape2_1.4.1      
[19] lambda.r_1.1.7       magrittr_1.5         scales_0.2.4        
[22] codetools_0.2-11     MASS_7.3-40          colorspace_1.2-6    
[25] stringi_0.4-1        RCurl_1.96-0         munsell_0.4.2    
```

**Comment by Geoff99** [comment] 2015-05-28 23:56
Hi @DarwinAwardWinner , Issue #623 should be fixed in the versions of `devtools` and `roxygen2` your `sessionInfo` report mentions, so it's probably not that.  

Just a guess - have you got `#' @include filename.r` type roxygen2 comments in your various files, to ensure that the collate sequence in the DESCRIPTION file is correct.  By default `devtools` loads files in alphabetical order of the filenames, which can lead to code being out of order and hence R may be trying to create a subclass before it knows about the superclass (if the correct collate order is not alphabetical). 

Or alternatively, if the missing superclass (`BiocParallelParam`) comes from another package, you might be missing an `#' @importClassesFrom whateverpkg BiocParallelParam` type statement.

Emphasise these are both just guesses.  Hope they help though.

**Comment by hadley** [comment] 2015-06-19 13:56
The problem is that you're using collate.unix and collate.windows which devtools doesn't know about. I'd be happy to accept a PR to add support (you'd need to patch https://github.com/hadley/devtools/blob/master/R/load-code.r#L40-L65). They're rare enough that I don't have the time to add support myself.

**Closed by hadley** 2015-06-19 13:56 UTC
