### ISSUE TITLE
install_bitbucket() needs a default 'quiet' value

### ISSUE THREAD

**Issue by plantarum** [hadley/devtools#1345] opened 2016-09-15 15:06 UTC
Hi,

Using the example on the `install_bitbucket` help page:

```
install_bitbucket("sulab/mygene.r@default")
```

Fails with:

```
Error in value[[3L]](cond) : argument "quiet" is missing, with no default
```

I think the problem is that the arguments of `install_bitbucket` are passed to `try_install_remote`, which requires a value for `quiet`:

```
install_bitbucket(repo, username, ref = "master", subdir = NULL, auth_user = NULL, 
   password = NULL, ...) 
-> install_remotes(remotes, ...) 
-> try_install_remote(..., quiet = quiet)
```

If we add `quiet` to install_bitbucket, the problem is solved: 

```
install_bitbucket("sulab/mygene.r@default", quiet = FALSE)
## works as expected
```

Adding a default `quiet` value to the `install_bitbucket` definition, as is the case in `install_github`, would fix this.

Best,

Tyler

**Comment by lucacerone** [comment] 2016-12-15 10:25
the same applies to install_git, it doesn't work anymore if you don't provide an argument to quiet

**Comment by hadley** [comment] 2017-08-02 20:52
Duplicate of #1346

**Closed by hadley** 2017-08-02 20:52 UTC
Labels: bug, install
