### ISSUE TITLE
install_github fails with "there is no package called 'Rcpp'"

### ISSUE THREAD

**Issue by jjallaire** [hadley/devtools#1492] opened 2017-04-07 12:24 UTC
For this repo: https://github.com/rstudio/rtutor, which has the following dependencies:

```
Imports:
  utils,
  parallel,
  withr,
  rappdirs,
  rprojroot,
  jsonlite,
  htmltools (>= 0.3.5),
  htmlwidgets,
  evaluate,
  knitr (>= 1.14),
  markdown,
  shiny (>= 1.0),
  rmarkdown (>= 1.4)
```

In a fresh R 3.3.3. installation on Windows 10 with nothing pre-installed save for devtools I get this error during `devtools::install_github("rstudio/rtutor")`:

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
```

The full transcript of the installation is here:

```
> devtools::install_github("rstudio/rtutor")
Downloading GitHub repo rstudio/rtutor@master
from URL https://api.github.com/repos/rstudio/rtutor/zipball/master
Installing rtutor
Installing 1 package: evaluate
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/evaluate_0.10.zip'
Content type 'application/zip' length 47761 bytes (46 KB)
downloaded 46 KB

package ‘evaluate’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: htmltools
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/htmltools_0.3.5.zip'
Content type 'application/zip' length 582845 bytes (569 KB)
downloaded 569 KB

package ‘htmltools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: htmlwidgets
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/htmlwidgets_0.8.zip'
Content type 'application/zip' length 848612 bytes (828 KB)
downloaded 828 KB

package ‘htmlwidgets’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: knitr
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/knitr_1.15.1.zip'
Content type 'application/zip' length 1003775 bytes (980 KB)
downloaded 980 KB

package ‘knitr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: markdown
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/markdown_0.7.7.zip'
Content type 'application/zip' length 167729 bytes (163 KB)
downloaded 163 KB

package ‘markdown’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: rappdirs
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rappdirs_0.3.1.zip'
Content type 'application/zip' length 79779 bytes (77 KB)
downloaded 77 KB

package ‘rappdirs’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: rmarkdown
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rmarkdown_1.4.zip'
Content type 'application/zip' length 2275092 bytes (2.2 MB)
downloaded 2.2 MB

package ‘rmarkdown’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: rprojroot
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rprojroot_1.2.zip'
Content type 'application/zip' length 58914 bytes (57 KB)
downloaded 57 KB

package ‘rprojroot’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
Installing 1 package: shiny
Installing package into ‘C:/Users/jjallaire/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/shiny_1.0.1.zip'
Content type 'application/zip' length 2753997 bytes (2.6 MB)
downloaded 2.6 MB

package ‘shiny’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jjallaire\AppData\Local\Temp\RtmpY1VFFJ\downloaded_packages
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/jjallaire/AppData/Local/Temp/RtmpY1VFFJ/devtools99c6b8533b4/rstudio-rtutor-ec6f5aa"  \
  --library="C:/Users/jjallaire/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'rtutor' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'Rcpp'
ERROR: lazy loading failed for package 'rtutor'
* removing 'C:/Users/jjallaire/Documents/R/win-library/3.3/rtutor'
Error: Command failed (1)
```

**Comment by jimhester** [comment] 2017-04-07 18:59
Thanks for the report JJ, I believe this is a known issue, see https://github.com/hadley/devtools/issues/1370#issuecomment-273570049 for some discussion of the cause. We should have a fix for this in the near future.

**Comment by jjallaire** [comment] 2017-04-08 11:33
Okay, great. Thanks!

**Closed** 2017-08-01 20:58 UTC
