### ISSUE TITLE
source_gist fails

### ISSUE THREAD

**Issue by statguy** [hadley/devtools#1376] opened 2016-10-16 07:51 UTC
Running source_gist fails:

> source_gist("9024152")
> Error in r_files[[which]] : invalid subscript type 'closure'

In run-source.R "which <- 1" at line 142 should be outside the if statement, otherwise "which" does not always get defined.

**Comment by hadley** [comment] 2016-11-03 15:17
Duplicate of #1266

**Closed by hadley** 2016-11-03 15:17 UTC
