### ISSUE TITLE
devtools::release()

### ISSUE THREAD

**Issue by coachshea** [hadley/devtools#858] opened 2015-06-23 19:04 UTC
when trying to use devtools::release() I continually get:

'error in git2r::status ... unused argument (verbose = FALSE)'

both devtools and git2r are recent versions

**Comment by hadley** [comment] 2015-06-23 21:43
Could you please give me the output of: `dr_devtools()` and `devtools:::git_uncommitted()`

**Comment by cboettig** [comment] 2015-06-26 05:23
This is an exact duplicate of https://github.com/hadley/devtools/issues/797 and has already been fixed in the GitHub version.

__However__, since that fix has not been released to CRAN, anyone using the latest copy of `devtools` and `git2r` from CRAN gets this error; which is super annoying since `release()` is basically broken in the CRAN version not that `git2r` version `0.10.1` is on CRAN.  So a new release to CRAN would be stellar ;-)

**Comment by hadley** [comment] 2015-06-26 11:28
It's on its way to CRAN now ;)

**Closed by hadley** 2015-06-26 11:28 UTC
