### ISSUE TITLE
install_local fails if package is not a git repository

### ISSUE THREAD

**Issue by varadharajan** [hadley/devtools#834] opened 2015-06-05 06:13 UTC
If i try to install "some-module" from a local directory, it fails with this error. I think git repository is not needed for those packages that are to be installed from local.

devtools version : 1.8.0
R version : 3.1.2

> install_local("some-module")
Error in validObject(.Object) :
  invalid class “git_repository” object: Invalid repository

**Comment by rmflight** [comment] 2015-06-05 12:22
but that is what `devtools::install()` is for, installing directly from either the current directory or a defined directory

**Comment by varadharajan** [comment] 2015-06-05 12:27
Doc mentions "install_local() from a local file on disk". I'm sorry, probably i'm mistaken, but isn't install_local meant for that?

**Comment by rmflight** [comment] 2015-06-05 12:52
not sure, but on my install of devtools (1.7.0), the example provided in `install_local` works fine, it installs a source copy of `testthat` correctly. Perhaps it is an issue with a directory vs a tarball? I would test to see what the issue is. It also may be that the documentation needs to be updated that it actually expects a *built* package as a tarball.

**Comment by varadharajan** [comment] 2015-06-05 13:06
Yeah.. It works fine with built packages. In devtools 1.6, it used to work fine with directories as well, but it now fails in 1.8 with the above failure. May be we can just update the docs with the details.

**Comment by rmflight** [comment] 2015-06-05 13:08
aha, if it used to work in 1.6 with directories, then you might have a legit issue. Imma let @hadley handle this.

I only chimed in when I saw this issue because I've only ever used `install`, and didn't even know about `install_local`.

**Comment by bachmeil** [comment] 2015-06-06 10:46
I'm using version 1.8. install_local installs without issue for one directory:

```
install_local("path/to/package1")
```

but fails for another:

```
install_local("path/to/package2")
```

returning

> Error in validObject(.Object) :
> invalid class “git_repository” object: Invalid repository

Both are git repos, and both packages install without issue using older versions of devtools. I don't have a tarball in either directory.

**Comment by sboehringer** [comment] 2015-06-12 14:56
I have the same problem.
I have re-run install_local on a local project which used to work. Now I get the above error. So this is definitely a regression. I am on devtools_1.8.0

A workaround for me is to zip up the package folder like so:
pkgPath = Sprintf('%{dir}Q/PredictionPenalized.tgz', dir = tempdir());
System(Sprintf('tar czf %{pkgPath}Q ../PredictionPenalized'), 2);
install_local(pkgPath);

**Comment by hadley** [comment] 2015-06-19 14:50
Probably fixed in #846

**Comment by hadley** [comment] 2015-06-23 21:45
Please try the dev version. If it still fails, please include the output of `traceback()`

**Comment by varadharajan** [comment] 2015-06-26 16:26
@hadley Sorry for the delay. I will update the thread by tomorrow.

**Comment by varadharajan** [comment] 2015-06-28 06:56
@hadley  Looks like its fixed in master branch. I'm able to install packages successfully.

**Comment by hadley** [comment] 2015-06-28 11:59
Great!

**Closed by hadley** 2015-06-28 11:59 UTC
