### ISSUE TITLE
Text of warning message omitted in `load_all` and `document`

### ISSUE THREAD

**Issue by davharris** [hadley/devtools#1451] opened 2017-01-29 23:23 UTC
In the reproducible example described below, `document` and `load_all` produce cryptic warnings:

```
Warning messages:
1: character(0) 
2: character(0) 
```

On the other hand, `R CMD INSTALL --no-multiarch --with-keep.source` includes the text of the warnings, which turn out to be namespace conflicts:

```
Warning: replacing previous import ‘dplyr::contains’ by ‘purrr::contains’ when loading ‘bug’
Warning: replacing previous import ‘dplyr::order_by’ by ‘purrr::order_by’ when loading ‘bug’
```

To reproduce, you just need to add `import(dplyr)` and `import(purrr)` to a package's NAMESPACE file and add both packages under `Imports` in the DESCRIPTION file. I've attached a copy of reproducible example that you can also try downloading in case there's something more subtle going on: [bug_0.1.0.tar.gz](https://github.com/hadley/devtools/files/737908/bug_0.1.0.tar.gz)

Thanks for writing/maintaining such a useful package!

```
Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-01-29                  

Packages -----------------------------------------------------------------------------
 package    * version     date       source                          
 assertthat   0.1         2013-12-06 CRAN (R 3.3.0)                  
 backports    1.0.5       2017-01-18 cran (@1.0.5)                   
 bug        * 0.1.0       <NA>       local                           
 DBI          0.5-1       2016-09-10 CRAN (R 3.3.0)                  
 devtools     1.12.0.9000 2017-01-29 Github (hadley/devtools@d8ab190)
 digest       0.6.12      2017-01-27 cran (@0.6.12)                  
 dplyr      * 0.5.0       2016-06-24 CRAN (R 3.3.0)                  
 magrittr     1.5         2014-11-22 CRAN (R 3.3.0)                  
 memoise      1.0.0.9001  2017-01-29 Github (hadley/memoise@884d565) 
 pkgbuild     0.0.0.9000  2017-01-29 Github (r-pkgs/pkgbuild@65eace0)
 pkgload      0.0.0.9000  2017-01-29 Github (r-pkgs/pkgload@def2b10) 
 purrr      * 0.2.2       2016-06-18 cran (@0.2.2)                   
 R6           2.2.0       2016-10-05 cran (@2.2.0)                   
 Rcpp         0.12.9      2017-01-14 cran (@0.12.9)                  
 roxygen2     5.0.1       2015-11-11 CRAN (R 3.3.0)                  
 rprojroot    1.2         2017-01-16 cran (@1.2)                     
 stringi      1.1.2       2016-10-01 CRAN (R 3.3.0)                  
 stringr      1.1.0       2016-08-19 cran (@1.1.0)                   
 tibble       1.2         2016-08-26 cran (@1.2)                     
 withr        1.0.2       2016-06-20 CRAN (R 3.3.0) 
```

**Comment by hadley** [comment] 2017-08-02 16:15
This appears to be a duplicate of https://github.com/r-lib/pkgload/issues/39

**Closed by hadley** 2017-08-02 16:15 UTC
Labels: bug, load
