### ISSUE TITLE
`install_github` fails when a private github repository is specified in the remote dependency.

### ISSUE THREAD

**Issue by dy-kim** [hadley/devtools#1381] opened 2016-10-28 06:40 UTC
#### [Description]
- `install_github` fails when a private GitHub repository is specified in the remote dependency.
  - The remote dependency is described in `DESCRIPTION` file as following
    ```R
    Remotes: 
        github::PRIVATE_ORG/PRIVATE_PKG
    ```
#### [Steps to Reproduce]
- This issue is related to a private github repository, try following steps with your own private one. (Be prepared with the `Personal Access Token (PAT)`)
- I'll give the instruction with the assumption that you have two private repositories named `banana` and `monkey`, and your GitHub username is `zookeeper`.
1. Put `Remotes: github::zookeeper/banana` in the `DESCRIPTION` file in the `monkey` R package.
2. Try `devtools::install_github("zookeeper/monkey")`

(Expected)
- First install `zookeeper/banana` and then `zookeeper/monkey`

(Actual)
- Fail to install `zookeeper/banana`
#### [Screenshots]
- This is an actual case of mine
- My private R package `JediETL` has a remote dependencies which contains several private GitHub repositories.

![image](https://cloud.githubusercontent.com/assets/8338562/19797135/1eeba0d8-9d24-11e6-862f-94cffa2ba3fe.png)

#### [Related Issues]
- hadley/devtools#1262

#### [Related Pull Requests]
- hadley/devtools#1263

**Comment by hadley** [comment] 2017-08-02 21:07
Likely to be duplicate of #1280

**Closed by hadley** 2017-08-02 21:07 UTC
Labels: bug, install
